//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paytrack.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paytrack.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than {0}..
        /// </summary>
        public static string Movement_Amount_GreaterThan {
            get {
                return ResourceManager.GetString("Movement_Amount_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must not have more than {0} digits in total and {1} decimal places..
        /// </summary>
        public static string Movement_Amount_PrecisionScale {
            get {
                return ResourceManager.GetString("Movement_Amount_PrecisionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be at most {0} characters..
        /// </summary>
        public static string Movement_Description_MaxLength {
            get {
                return ResourceManager.GetString("Movement_Description_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement ID is required..
        /// </summary>
        public static string Movement_Id_NotEmpty {
            get {
                return ResourceManager.GetString("Movement_Id_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement was not found..
        /// </summary>
        public static string Movement_NotFound {
            get {
                return ResourceManager.GetString("Movement_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than {0}..
        /// </summary>
        public static string Movement_PageNumber_GreaterThan {
            get {
                return ResourceManager.GetString("Movement_PageNumber_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be greater than {0}..
        /// </summary>
        public static string Movement_PageSize_GreaterThan {
            get {
                return ResourceManager.GetString("Movement_PageSize_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed {0}..
        /// </summary>
        public static string Movement_PageSize_Max {
            get {
                return ResourceManager.GetString("Movement_PageSize_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        public static string Movement_UserId_NotEmpty {
            get {
                return ResourceManager.GetString("Movement_UserId_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        public static string User_Currency_NotEmpty {
            get {
                return ResourceManager.GetString("User_Currency_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        public static string User_Email_AlreadyInUse {
            get {
                return ResourceManager.GetString("User_Email_AlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address..
        /// </summary>
        public static string User_Email_EmailAddress {
            get {
                return ResourceManager.GetString("User_Email_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be at most {0} characters long..
        /// </summary>
        public static string User_Email_MaxLength {
            get {
                return ResourceManager.GetString("User_Email_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string User_Email_NotEmpty {
            get {
                return ResourceManager.GetString("User_Email_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string User_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("User_Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at most {0} characters..
        /// </summary>
        public static string User_Password_MaxLength {
            get {
                return ResourceManager.GetString("User_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters..
        /// </summary>
        public static string User_Password_MinLength {
            get {
                return ResourceManager.GetString("User_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string User_Password_NotEmpty {
            get {
                return ResourceManager.GetString("User_Password_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone is required..
        /// </summary>
        public static string User_TimeZone_NotEmpty {
            get {
                return ResourceManager.GetString("User_TimeZone_NotEmpty", resourceCulture);
            }
        }
    }
}
