global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using RabbitMQ.Client;
global using Serilog;
global using Serilog.Context;
global using Serilog.Exceptions;
global using Serilog.Exceptions.Core;
global using Serilog.Exceptions.EntityFrameworkCore.Destructurers;
